services:
  web:
    build: ./backend
    command: gunicorn backend.wsgi:application --bind 0.0.0.0:8000
    expose:
      - 8000
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env

  nginx:
    image: nginx:latest
    ports:
      - "8000:80"
    volumes:
      - ./backend/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
