# Generated by Django 5.2.1 on 2025-05-22 19:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_profile_paid_profile_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='paid',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='verified',
        ),
    ]
