# Generated by Django 5.2.1 on 2025-08-01 13:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_remove_profile_paid_remove_profile_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='matric_number',
            field=models.CharField(),
        ),
    ]
