# Generated by Django 5.2.1 on 2025-05-22 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='certificate',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
