# Generated by Django 5.2.1 on 2025-06-21 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_certificate_approved'),
    ]

    operations = [
        migrations.CreateModel(
            name='ApprovedCertificate',
            fields=[
            ],
            options={
                'verbose_name': 'Approved Certificate',
                'verbose_name_plural': 'Approved Certificates',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dashboard.certificate',),
        ),
        migrations.CreateModel(
            name='PendingCertificate',
            fields=[
            ],
            options={
                'verbose_name': 'Pending Certificate',
                'verbose_name_plural': 'Pending Certificates',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('dashboard.certificate',),
        ),
    ]
